"""Add chemical dictionary

Revision ID: 14352da7d169
Revises: 3a264a5a792e
Create Date: 2016-08-02 21:02:51.979076

"""

# revision identifiers, used by Alembic.
revision = '14352da7d169'
down_revision = '3a264a5a792e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chem_dict',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('smiles', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chem_dict')
    ### end Alembic commands ###
