"""Add abbreviations

Revision ID: 164efab664ba
Revises: 5626ea423bf1
Create Date: 2016-03-14 01:27:28.956379

"""

# revision identifiers, used by Alembic.
revision = '164efab664ba'
down_revision = '5626ea423bf1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cde_job', sa.Column('abbreviations', postgresql.JSONB(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cde_job', 'abbreviations')
    ### end Alembic commands ###
