"""Remove unused fields

Revision ID: 3a264a5a792e
Revises: 164efab664ba
Create Date: 2016-04-17 23:06:07.363632

"""

# revision identifiers, used by Alembic.
revision = '3a264a5a792e'
down_revision = '164efab664ba'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cde_job', 'text')
    op.drop_column('cde_job', 'abbreviations')
    op.drop_column('cde_job', 'biblio')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cde_job', sa.Column('biblio', postgresql.JSONB(), autoincrement=False, nullable=True))
    op.add_column('cde_job', sa.Column('abbreviations', postgresql.JSONB(), autoincrement=False, nullable=True))
    op.add_column('cde_job', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
