"""Add registered user

Revision ID: 56fbdc935fd8
Revises: 14352da7d169
Create Date: 2016-10-03 19:27:23.668349

"""

# revision identifiers, used by Alembic.
revision = '56fbdc935fd8'
down_revision = '14352da7d169'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('affiliation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    ### end Alembic commands ###
